#! /bin/sh

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config single_monocle true # smart borders
bspc config borderless_monocle true # smart borders
bspc config gapless_monocle true # use "true" for smart gaps

bspc config focus_follows_pointer false
bspc config click_to_focus true # focus with any click

bspc config ignore_ewmh_focus true # prevent focus stealing

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a wicd-client state=pseudo_tiled


sxhkd -m 1 &

xrdb -merge ~/.Xresources

if [ "$(command -v feh 2> /dev/null)" ]; then
	feh --bg-fill ~/Téléchargements/6330951-minimalist-wallpaper.jpg
	wal -R
fi

if [ "$(command -v compton 2> /dev/null)" ]; then
	compton -b --config "$HOME/.config/compton.conf"
fi

if [ "$(command -v blueman-applet 2> /dev/null)" ]; then
        blueman-applet &
fi

$HOME/.config/polybar/launch.sh

# start music server
#if [ "$(command -v mpd 2> /dev/null)" ]; then
#	mpd
#fi
